# Generated by Django 4.2.7 on 2024-02-22 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserInterest",
        ),
    ]
