# Generated by Django 4.2.7 on 2024-02-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trail",
            name="link",
        ),
        migrations.AddField(
            model_name="trail",
            name="coordinates",
            field=models.JSONField(null=True),
        ),
    ]
