# Generated by Django 4.2.7 on 2024-02-22 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0002_remove_trail_link_trail_coordinates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrace",
            name="race",
        ),
        migrations.RemoveField(
            model_name="userrace",
            name="user",
        ),
        migrations.DeleteModel(
            name="Race",
        ),
        migrations.DeleteModel(
            name="UserRace",
        ),
    ]
