# Generated by Django 4.2.7 on 2024-02-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_remove_userrace_race_remove_userrace_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trail",
            name="coordinates",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
