# Generated by Django 4.2.7 on 2024-02-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_avatar_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("sunglasses", "Sunglasses"),
                    ("dog", "Dog"),
                    ("mountains", "Mountain"),
                    ("map", "Map"),
                    ("bottle", "Bottle"),
                    ("shoe", "shoe"),
                ],
                default="shoe",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Avatar",
        ),
    ]
