# Generated by Django 4.2.7 on 2024-02-21 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postlike",
            options={},
        ),
    ]
